(specifications->manifest
 '("python-mypy"
   "python-pandas"
   "python-pandas-flavor"
   "python-pandas-stubs"
   "python-pytest"
   "python-pytest-mypy"
   "python-toolz"
   "python-treelib"
   "python-wrapper"
   "which"))
